#!/bin/bash

echo -e "\e[1;33m 
Instale para sua arquitetura\e[1;35m
1 :x86
2 :arm
\e[m
"
read res
if [ $res == 1 ];
then
    wget https://go.dev/dl/go1.22.0.linux-386.tar.gz
    rm -rf /usr/local/go && tar -C /usr/local -xzf go1.22.0.linux-386.tar.gz
    export PATH=$PATH:/usr/local/go/bin
else
    wget https://go.dev/dl/go1.22.0.linux-arm64.tar.gz
    rm -rf /usr/local/go && tar -C /usr/local -xzf go1.22.0.linux-amd64.tar.gz
    export PATH=$PATH:/usr/local/go/bin
fi
