#!/bin/bash

export PATH=$PATH:/usr/local/go/bin

echo -e "\e[1;33m 
Instale para sua arquitetura\e[1;35m
1 :x86
2 :x86_64
3 :arm\e[m
"
read res
if [ $res == 1 ];
then
    wget https://go.dev/dl/go1.22.0.linux-386.tar.gz
    rm -rf /usr/local/go && tar -C /usr/local -xzf go1.22.0.linux-386.tar.gz
elif [ $res == 2 ];
then
    wget https://go.dev/dl/go1.22.0.linux-amd64.tar.gz
    rm -rf /usr/local/go && tar -C /usr/local -xzf go1.22.0.linux-amd64.tar.gz
else
    wget https://go.dev/dl/go1.22.0.linux-arm64.tar.gz
    rm -rf /usr/local/go && tar -C /usr/local -xzf go1.22.0.linux-arm64.tar.gz
fi
